// Auto generated by build.sh at Mon Dec  9 15:24:46 UTC 2013

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyVersion("14.0.1.1024")]
[assembly: AssemblyFileVersion("14.0.1.1024")]
[assembly: AssemblyInformationalVersion("See https://github.com/versionone/VersionOne.SDK.NET.ObjectModel/wiki")]

[assembly: AssemblyProduct("ObjectModel.Tests")]
[assembly: AssemblyTitle("VersionOne SDK.NET ObjectModel")]
[assembly: AssemblyDescription("VersionOne SDK.NET ObjectModel ObjectModel.Tests Release Build")]
[assembly: AssemblyCompany("VersionOne, Inc.")]
[assembly: AssemblyCopyright("Copyright 2008-2013, VersionOne, Inc., Licensed under modified BSD.")]

[assembly: AssemblyConfiguration("Release")]
